### ISSUE TITLE
Import fails when there is empty Suite or Test title

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/check-tests#130]
Users get error `Validation failed: Title cannot have only a blank title with only tags` when there are empty Suite or Test titles.

![image](https://github.com/testomatio/check-tests/assets/77803888/b872aad3-6f27-4786-bbac-3f8a94851ccb)

here is a link for slack thread https://testomatio.slack.com/archives/C013RBWCXJA/p1690447596532989

**Comment by DavertMik** [comment]
@TetianaKhomenko please check on `check-tests@0.8.20-beta.4`

**Comment by TetianaKhomenko** [comment]
The issue was fixed with `check-tests@0.8.20-beta.5`
