### ISSUE TITLE
Prepend_dir option doesn't consider the name correctly 

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/check-tests#132]
<img width="936" alt="Screenshot 2023-08-28 at 9 44 59 AM" src="https://github.com/testomatio/check-tests/assets/101338506/c8ec53ab-ce04-4854-bb3f-9e995d8ced37">
<img width="447" alt="Screenshot 2023-08-28 at 9 45 04 AM" src="https://github.com/testomatio/check-tests/assets/101338506/e4a7cfe1-4996-4c0b-a6c9-8ce3512034cd">

Instead of considering the folder as one , it is taking and splitting them into different folders

**Comment by olexandr13** [comment]
fixed in https://github.com/testomatio/check-tests/pull/138
appears in the next release
