### ISSUE TITLE
--no-empty option seems to be ignored on backend

### ISSUE THREAD

**Issue by tikolakin** [testomatio/check-tests#135]
**Describe the bug**
There seems to be a no way to get rid of empty test suites

**To Reproduce**
I have tried to import test with both options

<img width="1356" alt="Screenshot 2023-09-29 at 18 10 46" src="https://github.com/testomatio/check-tests/assets/5860505/3487d6b1-b62f-4a31-baa2-79b557602d59">
<img width="1451" alt="Screenshot 2023-09-29 at 18 09 18" src="https://github.com/testomatio/check-tests/assets/5860505/32540ce8-8d4c-4db0-8395-5ba9a1f128be">

After import - empty suite remains available
<img width="536" alt="image" src="https://github.com/testomatio/check-tests/assets/5860505/fdce2f86-27a8-4dc9-bdc3-60748c9352dd">

**Expected behavior**
When `noempty` is sent as true - Testomatio removes empty suites

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue was fixed. The fix will be published in the next release.

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin the fix is live now. Please check it and reply if it works for you.

**Comment by tikolakin** [comment]
It doesn't work, after importing with `--no-empty`. Tested with `https://github.com/testomatio/check-tests/releases/tag/0.8.24`
Empty folders/suites are created in testomatio
Also, recent changes seem to introduce a regression to the folder structure, prefixing it with the source folder. It wasn't like it before.

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue should be fixed now. Can we ask you to check it on new imports?
