### ISSUE TITLE
error while parsing imported type

### ISSUE THREAD

**Issue by olexandr13** [testomatio/check-tests#140]
![Image](https://github.com/testomatio/check-tests/assets/16742970/aa92c4dc-2df9-4d8e-8815-f98cc9a6bb2c)

**Comment by mykhailiukVitalii** [comment]
I have tested on the latest `npx check-tests@latest` and all as expected! + there are also tests that check this functionality.
Perhaps you forgot to SET `--typescript` opt
@olexandr13

Testing evidence:
1. switch to **examples/playwright**
2. command => TESTOMATIO_URL=https://beta.testomat.io TESTOMATIO=test-999 npx check-tests@latest Playwright "**/*{.,_}{test,spec,cy}.ts" --typescript  --update-ids

![Screenshot-1](https://github.com/testomatio/check-tests/assets/82405549/31b16b09-8ef5-40f0-8001-358963696c2c)
![Screenshot-2](https://github.com/testomatio/check-tests/assets/82405549/cee0a110-9caa-4f89-9162-0e33a501c2d0)

**Status PASS**
@TetianaKhomenko
