### ISSUE TITLE
tests with dynamic parameters are not uploaded correctly 

### ISSUE THREAD

**Issue by bheemvennapureddy** [testomatio/check-tests#141]
**Describe the bug**
tests with dynamic parameters are not uploaded correctly 

**To Reproduce**
Create a test of below format 
```
test.describe('New Loan Application', () => {
    const provinces = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'ON', 'SK'];
    provinces.forEach((state) => {
        test(`Validate New Loan Application for Specific Province ${state} @canpre`, async ({
```

**Expected behavior**
Should read the dynamic parameters and upload the tests 

**Screenshots**
<img width="884" alt="Screenshot 2023-11-07 at 4 13 17 PM" src="https://github.com/testomatio/check-tests/assets/144472943/43f83c7d-08cf-445c-a84d-9d10320051e5">

<img width="927" alt="Screenshot 2023-11-07 at 4 17 13 PM" src="https://github.com/testomatio/check-tests/assets/144472943/f80b8b9c-0d11-4d4e-9632-18f1531f5ca2">

**Comment by olexandr13** [comment]
@bheemvennapureddy CNR


![Image](https://github.com/testomatio/check-tests/assets/16742970/7e480432-dd49-4fb2-ab07-c25aadf9077d)

Please update `check-tests` and `reporter` to the latest version and retest, if issue still be reproduced - tag me here.
