### ISSUE TITLE
Parameter in parameterised test incorrectly parsed on API side

### ISSUE THREAD

**Issue by tikolakin** [testomatio/check-tests#147]
**Describe the bug**
Testomatio API incorrectly parse parameterised test value

**To Reproduce**
Execute parameterised test
Ex. request to API
```
{
  'artifacts': [],
   'code': None,
   'example': None,
   'message': None,
   'run_time': 0.7919288370176218,
   'stack': None,
   'status': None,
   'steps': None,
   'suite_id': None,
   'suite_title': 'test_local_file_operations_via_cli.py',
   'test_id': 'f30bd3b0',
   'title': 'Version 1.0.0 @Tf30bd3b0'
}
```

**Expected behavior**
Test is displayed in test run with `1.0.0` parameter

**Actual behaviour**
Test is displayed in test run with `1` parameter

**Screenshots**
<img width="862" alt="image" src="https://github.com/testomatio/check-tests/assets/5860505/ab7e5a76-46a0-4bdc-be21-d0b33ff8d549">
<img width="1141" alt="image" src="https://github.com/testomatio/check-tests/assets/5860505/66a2beff-0ad5-4959-9ea5-9f0b2343054d">

**Comment by tikolakin** [comment]
additionally, values with spaces are incorrectly handled as well. 
If value with spaces supplied - BE just takes value before first space and strip everything else

**Comment by DavertMik** [comment]
@tikolakin is this still relevant, can we close this?
