### ISSUE TITLE
Add support of import test.concurrent for parallelize in Jest

### ISSUE THREAD

**Issue by metroprog** [testomatio/check-tests#156]
If use parallelization of tests in one file - tests with `test.concurrent` ([Jest doc](https://jestjs.io/docs/api#testconcurrentname-fn-timeout)) do not immediately import into the testomat.io.
Workaround: first import simply `test` to assign an id, and then add `concurrent`

**Comment by olexandr13** [comment]
https://github.com/testomatio/check-tests/pull/195
