### ISSUE TITLE
Getting incorrect suite name when using serial notation

### ISSUE THREAD

**Issue by leandroefron** [testomatio/check-tests#158]
I have this suite notation to run tests on serial mode:

`test.describe.serial("Subscriptions page feature tests", {tag: ['@subs']}, async () => {`

When suite is imported from Testomat, it doesn't get the suite name and uses the file name (it's the second one):

<img width="724" alt="image" src="https://github.com/testomatio/check-tests/assets/8061144/16382fa9-ed2a-42d8-acfc-f8ae471a7051">

Note:
If I use this configuration:
`test.describe.configure({ mode: 'serial' });`

Suite is imported properly.

Note 2: 
Also with parallel notation is working properly:

`test.describe.parallel("Login page feature tests", {tag: ['@loginUser']}, async () => {`

Language: Typescript
Framework: Playwright

**Comment by DavertMik** [comment]
Fixed in check-tests latest which is 0.9.4

**Comment by TetianaKhomenko** [comment]
Hi @leandroefron! Can we ask you to try check-tests latest version 0.9.4? Thank you in advance!

**Comment by TetianaKhomenko** [comment]
Closing as fixed based on user's feedback.
