### ISSUE TITLE
High Security issues in babel-traverse & array-compare

### ISSUE THREAD

**Issue by shaneeiliaunloan** [testomatio/check-tests#177]
**Describe the bug**
Currently there's outstanding security issues with the version of babel-traverse and array compare dependancies. Could you please upgrade the versions? 

**To Reproduce**

**Expected behavior**
Use the latest versions of babel-traverse and array-compare

**Screenshots**
<img width="891" alt="image" src="https://github.com/user-attachments/assets/bb5c2b9e-4791-4f09-8c73-47051ee1609b">
**(note that the mout library is a dependancy of array-compare)**

**Comment by TetianaKhomenko** [comment]
Hi @shaneeiliaunloan! The issue is fixed in the latest check-tests version 0.9.6.
