### ISSUE TITLE
Error parsing {some test file}: SyntaxError: Unexpected token (42:9)

### ISSUE THREAD

**Issue by andreasciamanna** [testomatio/check-tests#18]
I'm running the command `TESTOMATIO={the_project_key} npx check-tests@latest Jest "**/*{.,_}{test,spec}.js" -d src/tests`.

The command manages to find only one valid test.

All other tests fail, apparently because the command does not understand JSX.

Here are a few examples where the checker throws the error:

```js
	it('has import now button', () => {
		const button_text = 'Push me!';
		render(<App buttonText={button_text}/>);
		expect(button()).not.toBeNull();
		expect(button().textContent).toEqual(button_text);
	});
```

```js
describe('Items to scan UI', () => {
	const items = ['plugin1', 'plugin2'];
	let onSelected;
	const render = () => shallow(<ItemsToScan heading={'heading'} items={items} onSelected={onSelected}/>);

	beforeEach(() => {
		onSelected = jest.fn();
	});
```

```js
describe('MO Scan on Localization page', () => {

	it('creates app', () => {
		const fileCount = 10;
		const filesToScan = {
			count: fileCount,
			plugins: ['plugin1'],
			themes: [],
			other: []
		};
		const expectedTitle = "WPML has detected changed or new MO files";

		const wrapper = shallow(
			<MOScanUILocalizationPage filesToScan={filesToScan}/>
		);
```

In all cases, it fails when it encounters some JSX (`<App buttonText={button_text}/>`, `<ItemsToScan`, `<MOScanUILocalizationPage`).

I don't know if that's a known limitation (from the docs, it doesn't look like it is) and how I can get around it.

Running Jest, of course, works without problems, as these are tests we have for a few years already.

I can share the source code if needed, but with other more private means, as it's from a commercial product.

**Comment by DavertMik** [comment]
I think this can be because of React syntax,
Additional babel plugin should be installed and listed to parse such files

**Comment by andreasciamanna** [comment]
@DavertMik hard to remember or know what I was doing almost a year ago :)

I'm not blaming you: since then, I hardly had the time to get back into Testomatio.

I hope I'll find that time in the next weeks, though.
