### ISSUE TITLE
Fixing tests to include the ID does not work

### ISSUE THREAD

**Issue by andreasciamanna** [testomatio/check-tests#21]
I've tried to add the test ID so to keep it in sync, then ran the check-test command again and got that:

![image](https://user-images.githubusercontent.com/181780/84125494-ea118d80-aa3c-11ea-9a79-6f8e4bd2d299.png)

I'm probably doing something wrong, but I'm not sure what this is.

**Comment by DavertMik** [comment]
I think this was fixed a while ago
