### ISSUE TITLE
Improve the support for it.each tests in Jest 

### ISSUE THREAD

**Issue by Mkots** [testomatio/check-tests#42]
After `test.each` support was added (#35) the new problem appeared. If the file has a `test.each` construction it will upload as one test with template string as name. This situation makes problems with runs because such type of test can't be matched on the platform.
The test parser should add every test from `test.each` construction as a separate test with the right ID

**Comment by DavertMik** [comment]
Unfortunately, there is no technical possibility to get all parameters from static analsis. 
So `test.each` will be always mapped to the same test 
But in test run reports it will be shown as different tests
