### ISSUE TITLE
Python py.test integration

### ISSUE THREAD

**Issue by poliarush** [testomatio/check-tests#60]
- auto assign ids from testomat
- manual ids assignment
- sync with testomat.io

Support following actions:
- Importing Into Project
- Disable Detached Tests
- Synchronous Import
- Auto-assign Test IDs in Source Code
- Keep Test IDs Between Projects
- Clean Test IDs
- Import Into a Branch
- Keep Structure of Source Code
- Delete Empty Suites
- Import Into a Specific Suite

**Comment by DavertMik** [comment]
Implemented as part of https://github.com/testomatio/pytestomatio
