### ISSUE TITLE
import process should not be fully failed due to some test with ID is not found

### ISSUE THREAD

**Issue by poliarush** [testomatio/check-tests#63]
- create a jest project 
- import tests
- update one test with ID manually in source doe
- import tests
- delete test with ID in testomat
- do import again

Expected failure to be shown however import process should be finished for other cases.

![image](https://user-images.githubusercontent.com/325722/85212871-64a0ae00-b357-11ea-8ff8-3368cba9f73b.png)

![image](https://user-images.githubusercontent.com/325722/85212877-73876080-b357-11ea-93ca-735966afe347.png)

![image](https://user-images.githubusercontent.com/325722/85212888-85690380-b357-11ea-88dc-6a3a56783e2c.png)

**Comment by poliarush** [comment]
@TetianaKhomenko please retest it

**Comment by TetianaKhomenko** [comment]
The issue was retested on check-tests v. 0.8.12 and verified as fixed
