### ISSUE TITLE
[newman-reporter] check tests for newman collection

### ISSUE THREAD

**Issue by olexandr13** [testomatio/check-tests#73]
- [x] test collection editing
- [x] implement update-ids
- [x] clean ids
- [x] unsafe clean
- [x] docs
- [x] unit tests
- [x] update examples project (to use folders)

**Comment by DavertMik** [comment]
```
check-newman **.json
```

**Comment by olexandr13** [comment]
Will try to integrate inside existent `check-tests` lib. In case of unsuccessful attempt will implement as separate lib.

**Comment by olexandr13** [comment]
https://github.com/testomatio/check-tests/pull/103
