### ISSUE TITLE
stable branch gives Node.js 12 deprecation warning

### ISSUE THREAD

**Issue by MikeMcC399** [testomatio/check-tests#79]
With `- uses: testomatio/check-tests@stable`, as documented in the [README.md](https://github.com/testomatio/check-tests/blob/master/README.md), GitHub issues a deprecation warning:

"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: testomatio/check-tests@stable. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/."

https://github.com/testomatio/check-tests/blob/0ea638fcec1820cf2e7b9854fdbdd04128a55bd4/action.yml#L48-L50

1. What is the current recommendation for using this action?  `- uses: testomatio/check-tests@???`
2. Will this JavaScript action be migrated to use `node16`?

**Comment by olexandr13** [comment]
already replaced with 14+

**Comment by MikeMcC399** [comment]
@olexandr13 
> already replaced with 14+

1. JavaScript actions can only run under certain Node.js versions offered by GitHub. Currently the only supported version is `node16`. See [runs.using for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions).
2. The [stable](https://github.com/testomatio/check-tests/commits/stable) branch recommended in the [README](https://github.com/testomatio/check-tests/blob/stable/README.md) was last updated in 2021 and it is 67 commits behind the master branch.

This issue is not fixed yet.

**Comment by MikeMcC399** [comment]
The [main](https://github.com/testomatio/check-tests/actions/workflows/main.yml) workflow shows this deprecation warning.

Also this workflow is using old versions of:
`actions/checkout@v1` => `v3`
`actions/setup-node@v2` => `v3`

**Comment by MikeMcC399** [comment]
This issue really has two parts:

1. #98 so I opened a new issue for this
2. In the [master](https://github.com/testomatio/check-tests/tree/master) branch the JavaScript node version still says `node12`

https://github.com/testomatio/check-tests/blob/71814ae41401bae1548134d87557b1e0204ea654/action.yml#L48-L50

So this needs to be changed from `using: 'node12'` to `using: 'node16'` and then tested.

**Comment by MikeMcC399** [comment]
@olexandr13 

I don't see that this issue is resolved. Could you explain where you think it is resolved?

`master` branch
https://github.com/testomatio/check-tests/blob/f7221e2095b9471dcbca2f664657c17b9db22a3e/action.yml#L48-L50

`stable` branch
https://github.com/testomatio/check-tests/blob/0ea638fcec1820cf2e7b9854fdbdd04128a55bd4/action.yml#L48-L50

**Comment by MikeMcC399** [comment]
Please reopen this issue.
