### ISSUE TITLE
[Playwright/Typescript] update-ids func inserts ids into import statements

### ISSUE THREAD

**Issue by sttaran** [testomatio/check-tests#80]
When I use typescript path aliases, updatei-ids doesn't work as expected. It inserts the suiteId on the first line that matches the `describe` title. In this case it's "Shift"

```ts
import {expect, Page, test} from '@playwright/test'
import Shift @Sff4de22bModel from '@src/models/ShiftModel'

test.describe('Shift', () => {
```

**Comment by poliarush** [comment]
@mykhailiukVitalii please put unit tests for such cases

**Comment by mykhailiukVitalii** [comment]
I have added PR which include 3 unit tests: ts & js files.
![Screenshot-test-1](https://user-images.githubusercontent.com/82405549/230672152-c9b3dc4e-a9f5-4d4a-8441-b2a8bf649ef5.png)

After the merge, we can start testing with the client.

**Comment by poliarush** [comment]
@DavertMik please provide beta version for client test

**Comment by mykhailiukVitalii** [comment]
Should be work as expected on the latest master/beta version = 0.8.17-beta-3

That's why I'm closing this ticket.

**Comment by poliarush** [comment]
@sttaran please check it
