### ISSUE TITLE
 [Playwright/Typescript] Last suiteId has been inserted for each describe with the same title

### ISSUE THREAD

**Issue by sttaran** [testomatio/check-tests#81]
In my current project, I have quite complex functionality that requires many tests with complex preconditions and actions. In order not to have test files for several thousand lines and 100 tests, I break such tests into files, but leave the same "describe/title" for all describes in each file.

They are normally imported to testomat. The problem occurs when I want to call update-ids.

Let's say I have test files _shifts1.spec.ts_, _shifts2.spec.ts_, _shifts3.spec.ts_. I have imported suites and it has the following structure in Testomat
- Shifts `@S1 `                               _shifts1.spec.ts_
   - With detailed capacity `@S1a`
- Shifts `@S2 `                           _shifts2.spec.ts_
   - Without detailed capacity `@S2a`
- Shifts `@S3`                           _shifts3.spec.ts_
   - Extra `@S3a`

When I call `npx check-tests@latest Playwright ....... --update-ids` 
`@S3` suiteId will be inserted into each file's root describe and child suites will not be mapped/inserted.

**Comment by mykhailiukVitalii** [comment]
Looks like this case has been fixed in the latest beta - 0.8.17-beta-3.
I'm closing this ticket now.

**Comment by poliarush** [comment]
@sttaran please check it
