### ISSUE TITLE
GH report error if create PR from fork

### ISSUE THREAD

**Issue by olexandr13** [testomatio/check-tests#86]
https://github.com/testomatio/check-tests/pull/83/checks

```
Error: Resource not accessible by integration
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/testomatio/check-tests/stable/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/home/runner/work/_actions/testomatio/check-tests/stable/index.js:119:7) {
  status: 403,
```

**Comment by olexandr13** [comment]
All attempts to fix were unsuccessful. Looks like requires enabling of `Enabling Advanced Security features` on GitHub.
No a user case, because reproduced only when create PR from a fork. With a PR within the same repo works fine.

**Comment by MikeMcC399** [comment]
@olexandr13 

Your [stable](https://github.com/testomatio/check-tests/tree/stable) branch which this is running against is two years old.
