### ISSUE TITLE
`stable` branch not updated since Sep 2021

### ISSUE THREAD

**Issue by MikeMcC399** [testomatio/check-tests#98]
This follows on from issue https://github.com/testomatio/check-tests/issues/79 "stable branch gives Node.js 12 deprecation warning".

The [stable](https://github.com/testomatio/check-tests/tree/stable) branch recommended in the [README](https://github.com/testomatio/check-tests/blob/stable/README.md) documentation is unchanged since commit https://github.com/testomatio/check-tests/commit/0ea638fcec1820cf2e7b9854fdbdd04128a55bd4 of @DavertMik on Sep 25, 2021.

See https://github.com/testomatio/check-tests/compare/stable...master

If fixes and features are added to the default [master](https://github.com/testomatio/check-tests/tree/master) branch, they will not be used by GitHub workflows such as [.github/workflows/main.yml](https://github.com/testomatio/check-tests/blob/master/.github/workflows/main.yml) in this repository.

https://github.com/testomatio/check-tests/blob/71814ae41401bae1548134d87557b1e0204ea654/.github/workflows/main.yml#L31

This can be seen in the "Set up job" job for instance in job [8219074452](https://github.com/testomatio/check-tests/actions/runs/4644056470/jobs/8219074452)

```text
Download action repository 'testomatio/check-tests@stable' (SHA:0ea638fcec1820cf2e7b9854fdbdd04128a55bd4)
```

from the full job log

```text
Current runner version: '2.303.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v1' (SHA:50fbc622fc4ef5163becd7fab6573eac35f8462e)
Download action repository 'actions/setup-node@v2' (SHA:1f8c6b94b26d0feae1e387ca63ccbdc44d27b561)
Download action repository 'testomatio/check-tests@stable' (SHA:0ea638fcec1820cf2e7b9854fdbdd04128a55bd4)
Complete job name: Check Tests
```

## Suggestion

Merge the latest release [0.8.12](https://github.com/testomatio/check-tests/releases/tag/0.8.12) into the [stable](https://github.com/testomatio/check-tests/tree/stable) branch.

**Comment by DavertMik** [comment]
Thanks, I will update it!

**Comment by MikeMcC399** [comment]
@DavertMik 

Are you still planning to do this?

The workflow  [.github/workflows/main.yml](https://github.com/testomatio/check-tests/blob/master/.github/workflows/main.yml) I referred to in the original post now has a syntax error in it and does not work anymore. (See job [5067947930](https://github.com/testomatio/check-tests/actions/runs/5067947930).)

![image](https://github.com/testomatio/check-tests/assets/66998419/91d0cae6-007f-400e-931c-a29c1733e050)

**Comment by MikeMcC399** [comment]
Stale issue.
We are no longer using the GitHub JavaScript Action `testomatio/check-tests@stable` which specifies the end-of-life `node12` version.
